### ISSUE TITLE
Crash when Adding Multiple Effects

### ISSUE THREAD

**Issue by InputandOutput** [QinomeD/spiceshelf#1]
Hello QinomeD,

I encountered a crash when adding multiple effects for a modded item; when I hover the mouse over the item in my inventory to display the effects, the game crashes with a null pointer exception. Here is the crash report: 
[crash-2023-07-20_22.03.43-client.txt](https://github.com/QinomeD/spiceshelf/files/12115639/crash-2023-07-20_22.03.43-client.txt)

Here is the contents of the json file for the modded item:
`{
    "item": "extradelight:mayo_jar_item",
    "effects": ["minecraft:resistance 20 1 false", "minecraft:slowness 5 1 false"]
}`

Please let me know if there is something wrong with my json file, if the crash is caused by it. Otherwise, having multiple effects on a particular spice would be helpful for balancing what spices to use for particular situations.

**Comment by QinomeD** [comment]
You can apply only one effect per condiment

**Comment by QinomeD** [comment]
But yeah I should probably do that

**Comment by QinomeD** [comment]
Update is now waiting for verification on CF!

Example:
```json
{
    "item": "minecraft:sugar",
    "effects": ["minecraft:speed 10 0 false", "minecraft:jump_boost 10 0 false"]
}
```
