### ISSUE TITLE
Condiment Stacks with Bottle Containers Consume the Whole Stack, Replacing the Stack with a Single Container

### ISSUE THREAD

**Issue by InputandOutput** [QinomeD/spiceshelf#2]
Hello QinomeD, I found another issue. 

When I assign the honey bottle to a food item and right click a stack of honey bottles on a food item while in my inventory, all the honey bottles are consumed and one bottle is left. I tested with modded bottles, which resulted in the same behavior. I would prefer if bottled condiment stacks are not consumed all at once to add to a food item in order to prevent accidental waste.

**Comment by QinomeD** [comment]
I... have no idea how this happened, I was pretty sure it worked just right

**Comment by QinomeD** [comment]
Also if you're already at it, try finding some other bugs, I don't want to release a new jar every hour :P

**Comment by QinomeD** [comment]
Fixed
