### ISSUE TITLE
Potency of Condiment Effect Does Not Display Properly

### ISSUE THREAD

**Issue by InputandOutput** [QinomeD/spiceshelf#3]
The potency of condiments does not show correctly (maybe a missing lang entry?). As shown below: 
![2023-07-21_11 33 57](https://github.com/QinomeD/spiceshelf/assets/34847260/9d87b344-3bac-4171-bf4b-22549c9b52f1)
Is it possible to fix/modify the content as to show different or readable information?

**Comment by QinomeD** [comment]
Ok, so I actually saw this one. And the thing is - it's the vanilla translation key. I don't even know how did it happen.

**Comment by QinomeD** [comment]
ok it's fixed now
